image: 
  name: hashicorp/terraform:1.9.2
  entrypoint: [""]

stages:
  - codescan
  - infra_validate
  - infra_deploy
  - lambda-redeploy
  - infra_destroy

codescan:
  image: 
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  stage: codescan
  script:
    - echo "Code scanning with Checkov"
    - checkov -d .
  allow_failure: true 
  rules:
    - when: always 

infra_validate:
  stage: infra_validate
  script:
    - cd infrastructure
    - terraform version
    - terraform init
    - terraform validate
  allow_failure: false
  rules:
    - when: always

infra_deploy:
  stage: infra_deploy
  script:
    - cd infrastructure
    - terraform init
    - terraform plan -out=terraform.tfplan
    - terraform apply -auto-approve terraform.tfplan
  allow_failure: false
  rules:
    - when: manual
  dependencies: 
    - infra_validate

lambda-redeploy:
  stage: lambda-redeploy
  script:
    - cd infrastructure
    - terraform init
    - terraform plan
    - terraform destroy -target=module.lambda --auto-approve
    - terraform destroy -target=module.eventBridge --auto-approve
    - terraform apply --auto-approve
  allow_failure: false
  rules:
    - changes: 
      - 'processing_code/*'
  dependencies: 
    - infra_deploy

infra_destroy:
  stage: infra_destroy
  script:
    - cd infrastructure
    - terraform init
    - terraform plan
    - terraform destroy --auto-approve
  allow_failure: false
  rules:
    - when: manual